CREATE TABLE SuperVillain (
Id INT IDENTITY(1, 1) NOT NULL,
VillainName VARCHAR(200) NULL,
Franchise VARCHAR(100) NULL,
Powers VARCHAR(1200) NULL,
ImageURL VARCHAR(2000) NULL
CONSTRAINT PK_SuperVillain PRIMARY KEY (Id)
)